### ISSUE TITLE
PyOpenGL-accelerate is missing

### ISSUE THREAD

**Issue by mirh** [open-cogsci/opensesame-windows-build-scripts#1]
So when expyriment tries to load PyOpenGL a warning is thrown
On the other hand, your [conda recipes](https://github.com/open-cogsci/opensesame-conda-recipes) have it everywhere

**Comment by smathot** [comment]
Could you provide some more information? I.e. what warning do you see exactly when Expyriment is loaded, and what makes you think that this is related to a missing dependency?

**Comment by mirh** [comment]
INFO:OpenGL.acceleratesupport:No OpenGL_accelerate module loaded: No module named 'OpenGL_accelerate'

If you try to `import OpenGL_accelerate` from the built-in python distro, it also fails. 
Now, it's not like this is the end of the world, but the oddest thing is that you are shipping it in other environments.

**Comment by smathot** [comment]
I just tested this on a Windows 10 system, and I don't see this warning. I can also import the module though:

```
from OpenGL import acceleratesupport
```

I suspect this is something specific to your system, i.e. a compatibility issue that causes the module to fail to load. Can you confirm this? Then I'll close the issue.

**Comment by mirh** [comment]
You should get the same message from the terminal if you first set the logging level to INFO.

**Comment by smathot** [comment]
You're right actually. And it also happens on my Ubuntu system. I looked up this error, and from what I understand it's not related to missing packages, but rather reflects some kind of incompatibility with the graphics card. So I'll close this issue, because I'm fairly sure that it's not packaging related (or specific to OpenSesame). Thanks for reporting it though!

**Comment by mirh** [comment]
Any kind of half-way modern gpu should support all the features you need outside of hard gaming. 

It is related to missing packages, as I said you aren't shipping pyopenGL-accelerate here (despite many of your recipes instead doing so). "No module named" means quite a specific thing.

**Comment by mirh** [comment]
Yup, it works now. 
```
Expyriment 0.10.0+opensesame2 (Python 3.7.6)
Main file: Lib\site-packages\opensesame.py (1d334d)
INFO:OpenGL.acceleratesupport:OpenGL_accelerate module loaded
INFO:OpenGL.arrays.arraydatatype:Using accelerated ArrayDatatype
```
And I'm kinda wondering if this couldn't mean xpyriment never *actually* used opengl till now.
